# Generated by Django 5.2.4 on 2025-08-31 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_remove_teacher_id_remove_teacher_subject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.IntegerField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=40)),
                ('Subject_detail', models.CharField(max_length=200)),
            ],
        ),
    ]
