# Generated by Django 5.2.4 on 2025-08-31 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='Subject_detail',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
