# Generated by Django 5.2.4 on 2025-08-31 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_alter_subject_subject_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(max_length=100),
        ),
    ]
