# Generated by Django 5.2.4 on 2025-09-01 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_alter_subject_subject_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='Subject_detail',
        ),
    ]
