# Generated by Django 5.2.4 on 2025-09-01 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_remove_subject_subject_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField()),
                ('subject_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.subject')),
            ],
        ),
    ]
