# Generated by Django 5.2.4 on 2025-09-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='id',
        ),
        migrations.AddField(
            model_name='detail',
            name='detail_id',
            field=models.IntegerField(default=4, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
