# Generated by Django 5.2.4 on 2025-09-01 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_remove_detail_id_detail_detail_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='subject_name',
            new_name='subject',
        ),
    ]
