# Generated by Django 5.2.4 on 2025-09-01 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_rename_subject_name_detail_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='subject',
        ),
    ]
